//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradingCompany.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBlockingData
    {
        public int UserId { get; set; }
        public int AdminId { get; set; }
        public string Reason { get; set; }
        public int TermInHours { get; set; }
        public Nullable<bool> BlockAndDelete { get; set; }
    
        public virtual tblUser tblUser { get; set; }
    }
}
